name: CI/CD Pipeline
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up node.js
        uses: actions/checkout@v3
        with:
          ndoe-version: 16
      - name: Install Dependency
        run: npm install
      - name: Run test
        run: npm test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: npm run deploy
